// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_HzqyD3r5yhW77vviZ6vxf3RA4a7Z5IM',
    appId: '1:245035868415:web:4f2b29afc9716431c0acca',
    messagingSenderId: '245035868415',
    projectId: 'flutterproject-12b13',
    authDomain: 'flutterproject-12b13.firebaseapp.com',
    storageBucket: 'flutterproject-12b13.appspot.com',
    measurementId: 'G-KG8JMTFE42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaGZ0E6PKfIblq7bImf8xPFP9iHEVk8_c',
    appId: '1:245035868415:android:f475f9dd58936a3bc0acca',
    messagingSenderId: '245035868415',
    projectId: 'flutterproject-12b13',
    storageBucket: 'flutterproject-12b13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsvY3Z6VGFEKKhzQInYf-vb32_fQym3p4',
    appId: '1:245035868415:ios:75e653a30789151dc0acca',
    messagingSenderId: '245035868415',
    projectId: 'flutterproject-12b13',
    storageBucket: 'flutterproject-12b13.appspot.com',
    iosClientId: '245035868415-f2t58n0rfnsjui4cblukujnfqrd42p7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsvY3Z6VGFEKKhzQInYf-vb32_fQym3p4',
    appId: '1:245035868415:ios:b85f0ef0f9574c43c0acca',
    messagingSenderId: '245035868415',
    projectId: 'flutterproject-12b13',
    storageBucket: 'flutterproject-12b13.appspot.com',
    iosClientId: '245035868415-j7mmr7a6u9dtpqbnikp4od0ls5cn32b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
